### ISSUE TITLE
Release of the dataset/code

### ISSUE THREAD

**Issue by s-jse** [idiap/News-Media-Reliability#1]
Hi,

This is a very interesting paper, and I would love to use its results in our research project.
Is there a timeline on the release of the resulting dataset, or the processing scripts?
Thank you.

**Comment by sergioburdisso** [comment]
Hi there!

I'm glad you're interested in our work! :)

Yes, the paper will be officially presented at NAACL in three weeks (June 16th - 21st) and the source code will be released the week before so it is ready for NAACL. I'll let you know as soon as it is released, don't worry 💪 (and sorry for the delay in the response, I'm not yet added as a project member of this repo so I wasn't notified).

Thank you for your interest! 😃😃😄

PS: if you really need it earlier than in two weeks, let me know, I can check internally if it is possible to release it before NAACL.

**Comment by s-jse** [comment]
Thank you for your reply!
We are working to submit our paper by June 15th, and it would be great if we could use and cite the results of your paper there.
Even just the calculated reliability scores for news sources (without the source code) would be really helpful.

**Comment by sergioburdisso** [comment]
I see, if it is only the computed reliability scores shouldn't be a problem! we're glad you find our resource useful. Shall I send it to your e-mail (sinaj@cs.stanford.edu, right?) or you prefer different method for sharing it?

**Comment by s-jse** [comment]
> I see, if it is only the computed reliability scores shouldn't be a problem! we're glad you find our resource useful. Shall I send it to your e-mail ([sinaj@cs.stanford.edu](mailto:sinaj@cs.stanford.edu), right?) or you prefer different method for sharing it?

Yes, that would be wonderful, thank you very much!

**Comment by sergioburdisso** [comment]
_(the repo content is now available)_
